server:
  port: 8081

spring:
  application:
    name: client1
  jackson:
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
  rabbitmq:
    host: 139.196.202.149
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      host: 139.196.202.149
      port: 27017
      database: devicedb
      #uri: mongodb://139.196.202.149:27017/devicedb?maxpoolsize=10&minpoolsize=1&maxidletimems=600000&
      username: root
      password: '123456'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
